---
name: Build and Cache
description: This composite action runs build command and rtestores from cache if available.

runs:
  using: 'composite'

  steps:
    - name: cache and restore "figma plugin build result"
      id: cache_figma_build_results
      uses: actions/cache@v4
      with:
        path: |
          ./packages/plugin-figma/build
          ./packages/plugin-figma/manifest.json
        key: cache-build-results-${{ runner.os }}-${{ hashFiles('yarn.lock', './packages/plugin-figma/**/*.ts', './packages/plugin-figma/**/*.tsx', './packages/sync-*/**/*.ts', './packages/core/**/*.ts') }}
        restore-keys: |
          cache-build-results-${{ runner.os }}-${{ hashFiles('yarn.lock', './packages/plugin-figma/**/*.ts', './packages/plugin-figma/**/*.tsx', './packages/sync-*/**/*.ts', './packages/core/**/*.ts') }}
          cache-build-results-${{ runner.os }}-
          cache-build-results--

    - if: steps.cache_build_results.outputs.cache-hit != 'true'
      run: yarn build
      shell: bash
