---
name: Build and Cache
description: This composite action runs build command and rtestores from cache if available.

runs:
  using: 'composite'

  steps:
    - name: cache turborepo
      uses: actions/cache@v4
      with:
        path: |
          .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: cache and restore "build result"
      id: cache_build_results
      uses: actions/cache@v4
      with:
        path: |
          ./**/build
        key: cache-build-results-${{ runner.os }}-${{ hashFiles('**/*.ts', '**/*.tsx', '**/*.css', '**/package.json', 'yarn.lock') }}
        restore-keys: |
          cache-build-results-${{ runner.os }}-${{ hashFiles('**/*.ts', '**/*.tsx', '**/*.css', '**/package.json', 'yarn.lock') }}
          cache-build-results-${{ runner.os }}-
          cache-build-results--

    - if: steps.cache_build_results.outputs.cache-hit != 'true'
      run: yarn build
      shell: bash
